### ISSUE TITLE
NoGUI interface (headless SBC)

### ISSUE THREAD

**Issue by GoesInCircles** [Windows200000/TwitchDropsMiner-updated#115]
I run the source on raspberry3, because of efficiency instead of running it on main PC.
After solving all dependencies, app asked for display, so I had to install desktop and rdp just for this app.

Here comes my feature request, would it be possible that after initial setup we can run it no gui only via command line? Maybe even allow import zipped settings via command line?

Thanks for consideration

**Comment by Windows200000** [comment]
From README.md:

>TDM is not intended for/as:
>
>- Mining channel points - again, it's about the drops: only. The current points you're getting are a byproduct of getting the drops, not the main goal of it.
>- Mining anything else besides Twitch drops - no, I won't be adding support for a random 3rd party site that also happens to rely on watching Twitch streams.
>- Unattended operation: worst case scenario, it'll stop working and you'll hopefully notice that at some point. Hopefully.
>- 100% uptime application, due to the underlying nature of it, expect fatal errors to happen every so often.
>- Being hosted on a remote server as a 24/7 miner.
>- Being used with more than one managed account.
>- Mining campaigns the managed account isn't linked to.
