### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Nollasko** [Windows200000/TwitchDropsMiner-updated#119]
Worked fine for days but not even starting with this output

14:23:42: Fatal error encountered:
14:23:42: 
14:23:42: Traceback (most recent call last):
14:23:42:   File "main.py", line 160, in main
14:23:42:   File "twitch.py", line 772, in run
14:23:42:   File "twitch.py", line 923, in _run
14:23:42:   File "twitch.py", line 1749, in get_live_streams
14:23:42:   File "twitch.py", line 1750, in <listcomp>
14:23:42:   File "channel.py", line 116, in from_directory
14:23:42: TypeError: 'NoneType' object is not subscriptable

**Comment by Windows200000** [comment]
#118
