### ISSUE TITLE
Cookie Jar

### ISSUE THREAD

**Issue by sendrou** [Windows200000/TwitchDropsMiner-updated#120]
Is it possible to somehow not log into account, but use cookies or OAuth?

**Comment by Windows200000** [comment]
@sendrou For whatever reason the cookies is saved as a jar when it's actually binary. It's saved using pickle.

Why would you want that? Afaik, the reason it uses the current way, is because it currently has to pretend to be a TV or some such, because they added additional checks to browsers.

**Comment by sendrou** [comment]
@Windows200000 to launch many accounts easier, I already have pkl cookies, but they only have OAuth and persistent

**Comment by Windows200000** [comment]
From README.md:

>TDM is not intended for/as:
>
>- Mining channel points - again, it's about the drops: only. The current points you're getting are a byproduct of getting the drops, not the main goal of it.
>- Mining anything else besides Twitch drops - no, I won't be adding support for a random 3rd party site that also happens to rely on watching Twitch streams.
>- Unattended operation: worst case scenario, it'll stop working and you'll hopefully notice that at some point. Hopefully.
>- 100% uptime application, due to the underlying nature of it, expect fatal errors to happen every so often.
>- Being hosted on a remote server as a 24/7 miner.
>- Being used with more than one managed account.
>- Mining campaigns the managed account isn't linked to.
