### ISSUE TITLE
Notifications about claiming drops not working

### ISSUE THREAD

**Issue by kilroy98** [Windows200000/TwitchDropsMiner-updated#123]
It's started when Twitch start changing drops system.

**Comment by Windows200000** [comment]
Is this just #86?

**Comment by kilroy98** [comment]
I don't know. I mean when Drop is received, a popup notification was shown.

**Comment by kilroy98** [comment]
There are no logs, and no screenshots (I don’t understand the screenshot of what exactly). In the settings there is an item "Tray notifications", I mean it. Previously, before Twitch started changing the drop system, after receiving a drop, there was a pop-up notification in the system that the drop was received, but now for some reason they do not work.

This is probably the code responsible for this function.
https://github.com/Windows200000/TwitchDropsMiner-updated/blob/0f42b24864caeabc2af71a651c72f4b1d7fefadd/twitch.py#L1357-L1358

**Comment by Windows200000** [comment]
@kilroy98 Ohh, yeah this is 99% #85. Basically, the "ordinary" way in which TDM used to claim drops is never triggered. I haven't looked into that too deeply yet.
