### ISSUE TITLE
More Flags of Antivirus softwares

### ISSUE THREAD

**Issue by barbiehunter** [Windows200000/TwitchDropsMiner-updated#132]
I was wondering why the Program isn't really working for me at all as i realized my Windows detected the Software as virus. Trying to Re-Install it (Brave) Detects it in the Browser itself as Virus Already. Checking on [Virustotal ](https://www.virustotal.com/gui/file/0807b24b9894d3a936318a65b2274161375bf91a95389ff42f0b25eb742fa77d/detection)or [Triage](https://tria.ge/240615-zt6v2atgkf/behavioral1) shows it get hardly Flagged. May need to be some changed to be done against that. ( Good Luck with your Exam btw)

**Comment by Windows200000** [comment]
TDM has always been getting flagged. It's unsigned and Windows defender doesn't like pyinstaller. For more info, look through [issues in the original repo](https://github.com/DevilXD/TwitchDropsMiner/issues?q=is:issue+antivirus).

Unlike DevilXD, I consider modern Windows Defender good, as it has the largest install base and gets automatically updated, so it has a good library of signatures. Unlike some other antiviruses, it's just not as foolproof, but if you are somewhat educated, things like blocking suspicious websites to not download anything in the first place won't be much use to you.
