### ISSUE TITLE
The reward for not completing the next quest stays stuck here.

### ISSUE THREAD

**Issue by fgr178707** [Windows200000/TwitchDropsMiner-updated#133]
![image](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/109357981/1195df37-69a0-46a2-b338-6e73fc4f647c)

The reward for not completing the next quest stays stuck here.

You can only do this by re-running the software

After restarting the software and continuing that reward

![image](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/109357981/fe1bfb30-bfbd-47f2-9e5a-bca8307db173)

**Comment by epsgerry02** [comment]
same╮(╯▽╰)╭

**Comment by zelda0079** [comment]
This is twitch drop bug, you cannot get twitch drop of Sea of thieves even use idle it on broswer.

**Comment by fgr178707** [comment]
> This is twitch drop bug, you cannot get twitch drop of Sea of thieves even you use idle it on broswer.

That's right.
