### ISSUE TITLE
Farm without linking 

### ISSUE THREAD

**Issue by auuruum** [Windows200000/TwitchDropsMiner-updated#136]
Hey is it possible to farm twitch drops without linking it will be really cool feature

**Comment by Nixeld** [comment]
Set `self.linked` to True in `inventory.py` and build the application yourself.
![image](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/18643932/cf44c0e9-f0d5-4f54-a53e-0f10255ab345)

**Comment by Windows200000** [comment]
@auuruum Is there a game, that you cannot create an account for before buying?

Other than that:

From README.md:

>TDM is not intended for/as:
>
>- Mining channel points - again, it's about the drops: only. The current points you're getting are a byproduct of getting the drops, not the main goal of it.
>- Mining anything else besides Twitch drops - no, I won't be adding support for a random 3rd party site that also happens to rely on watching Twitch streams.
>- Unattended operation: worst case scenario, it'll stop working and you'll hopefully notice that at some point. Hopefully.
>- 100% uptime application, due to the underlying nature of it, expect fatal errors to happen every so often.
>- Being hosted on a remote server as a 24/7 miner.
>- Being used with more than one managed account.
>- Mining campaigns the managed account isn't linked to.
