### ISSUE TITLE
TDM detecting already claimed drops as available and idling for completed Campaigns

### ISSUE THREAD

**Issue by RainOne** [Windows200000/TwitchDropsMiner-updated#140]
### Description

TDM is detecting drops that I already got as "drops to get" and is idling for drops that I already got. Issue could be related to a weird behavior that Twitch is presenting:

Yesterday, I finished my last overwatch drop from the current batch of rewards. However, here's something strange: 

![chrome_hSV2pjOrk9](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/7484546/1711813d-a339-427a-8f3a-c52c2026abb7)![chrome_CEbAtvkaWx](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/7484546/c8f5091c-1ef6-4d96-b8f0-9b5c335a4cd0)![chrome_nSZz4Zebeu](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/7484546/8022f5fb-c4aa-404b-8ccd-527d6a85d399)

For some reason, my Rose gold Mercy is listed as being acquired "2023 years ago".  My Dragon Skin Polearm (from The Finals) also shows up as complete 2023 years ago: 

![chrome_l5JgKiZieC](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/7484546/007d7c47-61a1-4110-901c-28e7ad02ed72)

However, for some reason, the app only sees one of my Overwatch drops (it ignores both the one that says 2023 and the one that says 7 days ago) and my The Finals drop: 

![vncviewer_DcFeWUVn7G](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/7484546/4c40c88e-bd18-43c9-9411-5fecb0977f9f)

Therefore, it is farming the Overwatch 2 drop. Since I already got it, twitch.tv/inventory page doesn't show any overwatch 2 progress, which is expected. I do have Overwatch 2 listed on my priority drops, but that's working properly - it's just not identifying that I already have some drops.

### To Reproduce

Run TDM and see it farming for things I already have. Check "inventory" tab and see that it didn't detect dropped items as acquired.

### Expected behavior

TDM should have detected already acquired items.

### Observed behavior

TDM doesn't detect already acquired items (may or may not be related to weird "item acquired 2023 years ago" twitch description of said item)

### OS

Raspbian Linux

### Build

git clone, git pull for updates, running it through python

### Version/Commit

v15.7.0 / 84f4882

**Comment by notNSANE** [comment]
can confirm. 

this is critical since it's blocking other drops

**Comment by gibbed** [comment]
Yeah, I'm seeing strange entries for "2,023 years ago" for many recently acquired drops. This seems to directly correlate to which games the miner tries to work on that are already complete.

**Comment by Windows200000** [comment]
@RainOne @notNSANE  @gibbed I have a bit of time during the weekend so I will look at it tmrw.

A GQL query log, as described in the bug request form (`-vvv --debug-gql --debug-ws --log`) would be hugely helpful here, so I can see what data Twitch is sending the miner, once I get to work diagnosing the issue.
