### ISSUE TITLE
Probably a Virus

### ISSUE THREAD

**Issue by Furry0x057** [Windows200000/TwitchDropsMiner-updated#141]
### Description

https://www.hybrid-analysis.com/sample/ce79be8903fcd2d40cca22c7c61e32005661d1d9909ff7c885f37c3cff55bc16/6681582b62efec62e102f4fb
Contains ability to capture screen (API string)
Calls an API typically used for taking snapshot of the specified processes 
Calls an API possibly used to take screenshots 
Contains string like password/secret 
Found strings related to keylogger 

### To Reproduce

Contains ability to capture screen (API string)
Calls an API typically used for taking snapshot of the specified processes 
Calls an API possibly used to take screenshots 
Contains string like password/secret 
Found strings related to keylogger 

### Expected behavior

Contains ability to capture screen (API string)
Calls an API typically used for taking snapshot of the specified processes 
Calls an API possibly used to take screenshots 
Contains string like password/secret 
Found strings related to keylogger 

### Observed behavior

Contains ability to capture screen (API string)
Calls an API typically used for taking snapshot of the specified processes 
Calls an API possibly used to take screenshots 
Contains string like password/secret 
Found strings related to keylogger 

### OS

Any Windows x64 

### Build

.exe

### Version/Commit

latest

**Comment by barbiehunter** [comment]
I did a Issue about the "antivirus" thing myself, got answered severeal Times in the main repo. 
https://github.com/DevilXD/TwitchDropsMiner/issues?q=is:issue+antivirus
based on yourself to use the program or not, its open source so you can check it yourself^^
