### ISSUE TITLE
It seems the miner cannot get the newer twitch drop

### ISSUE THREAD

**Issue by zelda0079** [Windows200000/TwitchDropsMiner-updated#142]
### Description

It seems the miner cannot get the newer twitch drop unless you idle the twitch drop in website firstly.

### To Reproduce

1. Go to inventory tab, cannot find black desert.
2. Go to twitch website and watch stream of black desert.
3. Go back the miner, you can find black desert now.

### Expected behavior

Inventory tab can find newer twitch drop.

### Observed behavior

 Inventory tab cannot find newer twitch drop.

### Screenshots

Before:
![Twitch_Drops_Miner_(by_DevilXD)_BzySoWEYZf](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/19840375/94acddc8-b9db-4b41-b593-100100ab9361)
After:
![Twitch_Drops_Miner_(by_DevilXD)_893QGE8cHV](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/19840375/b0ffaf0a-dd02-409e-8a02-589302eb05ef)

### Logs

No logs.

### OS

WIN10

### Build

exe

### Version/Commit

[6a9f51c](https://github.com/Windows200000/TwitchDropsMiner-updated/commit/6a9f51c015e2797fade92ebb0a6c8231c14920c0)

**Comment by zelda0079** [comment]
And https://github.com/Windows200000/TwitchDropsMiner-updated/commit/84f48827baf6397771ac37ef591be9a72f15c8de cannot get procress of the twitch drop. However, https://github.com/DevilXD/TwitchDropsMiner/commit/14a9154366d2651dc2cf75903744553a64319eb3 is working.

**Comment by zelda0079** [comment]
> Looks like black desert might then be one of those repeat drops, that are claimed multiple times, instead of being a new but same drop. This definitely falls under #139.

Not only black desert, other newer twitch drop alse can't be found.

**Comment by Windows200000** [comment]
Well there is only one change that should only affect repeat drops. I'll make a more precise wonky patch in a bit, that should only allow the specific false date they report through as claimed.
