### ISSUE TITLE
What's the difference between this fork and the original?

### ISSUE THREAD

**Issue by DealsBeam** [Windows200000/TwitchDropsMiner-updated#146]
I'm curious to know

**Comment by T4bletopG4mes** [comment]
Gets updated way more often and has dark mode from what I've seen.

**Comment by DealsBeam** [comment]
Thanks, would be cool just to merge into one since it's essentially the same thing.

**Comment by notNSANE** [comment]
> Thanks, would be cool just to merge into one since it's essentially the same thing.

og dev doesntyhave time to update the app, we got this one meanwhile. Twitch changes every other week

**Comment by Windows200000** [comment]
@DealsBeam The main one does not work currently, while this one does. I'ts still a bit till I have time to work on this more again. (#127)
