### ISSUE TITLE
Not finding any Campaigns

### ISSUE THREAD

**Issue by Master-of-Illusion** [Windows200000/TwitchDropsMiner-updated#149]
### Description

21:21:18: No active campaigns to mine drops for. Waiting for an active campaign...
21:21:33: No active campaigns to mine drops for. Waiting for an active campaign...
21:21:53: No active campaigns to mine drops for. Waiting for an active campaign...
21:22:42: No active campaigns to mine drops for. Waiting for an active campaign...

In settings a choose priority only and added my game with twitch drops, it's didn't work.

### To Reproduce

Idk...

### Expected behavior

Twitch Drops mining.

### Observed behavior

idk ._.

### Screenshots

![изображение](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/175349967/5cc597b0-8bc5-458a-97b2-b552f2a8d2b8)
![изображение](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/175349967/9a769575-5429-497a-a6f4-a99305b60629)

### Logs

[debug.txt](https://github.com/user-attachments/files/16182409/debug.txt)

### OS

W10

### Build

.exe (with and w/o admin permissions)

### Version/Commit

v16.dev.8f3b6bd

### Additional context

Fix pls

**Comment by Windows200000** [comment]
BEcause WG account isn't linked?

**Comment by Master-of-Illusion** [comment]
> BEcause WG account isn't linked?

Make it mine without being tied to an account please, or it just don't collect, if your account isn't linked.

**Comment by Windows200000** [comment]
@Master-of-Illusion From README.md:

>TDM is not intended for/as:
>
>- Mining channel points - again, it's about the drops: only. The current points you're getting are a byproduct of getting the drops, not the main goal of it.
>- Mining anything else besides Twitch drops - no, I won't be adding support for a random 3rd party site that also happens to rely on watching Twitch streams.
>- Unattended operation: worst case scenario, it'll stop working and you'll hopefully notice that at some point. Hopefully.
>- 100% uptime application, due to the underlying nature of it, expect fatal errors to happen every so often.
>- Being hosted on a remote server as a 24/7 miner.
>- Being used with more than one managed account.
>- Mining campaigns the managed account isn't linked to.
