### ISSUE TITLE
Fatal error encountered...application terminated 

### ISSUE THREAD

**Issue by T4bletopG4mes** [Windows200000/TwitchDropsMiner-updated#154]
### Description

No idea what causes it but I just noticed it and it seems to have started happening recently.

### To Reproduce

Maybe its related with the No Man's Sky drops, not sure.

### Expected behavior

Should say "no drops available to mine currently" since Im dont have any for now.

### Observed behavior

See screenshot.

### Screenshots

![image](https://github.com/user-attachments/assets/8a1435ec-adbb-4b7c-b604-fce1b15f68fb)

### Logs

21:22:22: Fatal error encountered:
21:22:22: 
21:22:22: Traceback (most recent call last):
21:22:22:   File "main.py", line 160, in main
21:22:22:   File "twitch.py", line 772, in run
21:22:22:   File "twitch.py", line 817, in _run
21:22:22:   File "twitch.py", line 1670, in fetch_inventory
21:22:22:   File "asyncio\tasks.py", line 571, in _wait_for_one
21:22:22:   File "twitch.py", line 1608, in fetch_campaigns
21:22:22:   File "twitch.py", line 1575, in gql_request
21:22:22: exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]
21:22:22: 
21:22:22: Exiting...
21:22:23: 
21:22:23: Application Terminated.
21:22:23: Close the window to exit the application.

### OS

Windows 10 (64-bit)

### Build

.exe

### Version/Commit

v15.7.1

**Comment by IRhoAias** [comment]
Same Here
![image](https://github.com/user-attachments/assets/4177b19b-77ca-489e-ba0e-9ef925e1cc4a)

**Comment by gibbed** [comment]
Looking at the request from the miner vs Twitch itself, it looks like the sha256Hash for the persisted query has changed:

Old:

```json
{'persistedQuery': {'version': 1, 'sha256Hash': 'e5916665a37150808f8ad053ed6394b225d5504d175c7c0b01b9a89634c57136'}}
```

New:

```json
{"persistedQuery":{"version":1,"sha256Hash":"e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54"}}
```

**Comment by Windows200000** [comment]
@gibbed we were looking at it at the same time. This is technically a duplicate, but I will leave it, because the old issue is a very random crash that could be due to a slow rollout of this hash change, but oculd also be unrelated. Fix will be out in in-dev seeon. I'll also make a release for it.

**Comment by gibbed** [comment]
> @gibbed we were looking at it at the same time. This is technically a duplicate, but I will leave it, because the old issue is a very random crash that could be due to a slow rollout of this hash change, but oculd also be unrelated. Fix will be out in in-dev seeon. I'll also make a release for it.

This specific issue was opened recently which is why I replied to it specifically rather than an older one since it was likely the OP was referring to the new issue specifically; but yeah, thanks for the quick fixing!

**Comment by Windows200000** [comment]
[in-dev](https://github.com/Windows200000/TwitchDropsMiner-updated/releases/tag/dev-build) works, I will close this once it's in master.

**Comment by Skyl3lazer** [comment]
Here it is again 

15:00:19: Fatal error encountered:
15:00:19: 
15:00:19: Traceback (most recent call last):
15:00:19:   File "twitch.py", line 1736, in get_live_streams
15:00:19:   File "twitch.py", line 1575, in gql_request
15:00:19: exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]
15:00:19: 
15:00:19: The above exception was the direct cause of the following exception:
15:00:19: 
15:00:19: Traceback (most recent call last):
15:00:19:   File "main.py", line 160, in main
15:00:19:   File "twitch.py", line 772, in run
15:00:19:   File "twitch.py", line 923, in _run
15:00:19:   File "twitch.py", line 1747, in get_live_streams
15:00:19: exceptions.MinerException: Game: albion-online
15:00:19: 
15:00:19: Exiting...
15:00:20: 
15:00:20: Application Terminated.
15:00:20: Close the window to exit the application.

 
 on 8/7

**Comment by gibbed** [comment]
> Here it is again

#159
