### ISSUE TITLE
Maybe another hash has to be changed

### ISSUE THREAD

**Issue by woctezuma** [Windows200000/TwitchDropsMiner-updated#156]
### Suggestion(s)

I have noticed a second hash was changed in the original repository. See the following commit:
- https://github.com/DevilXD/TwitchDropsMiner/commit/97686353d415471668ae95440fa2fd896394c062

To be compared to the current state of your repository:
https://github.com/Windows200000/TwitchDropsMiner-updated/blob/69d73bec3acd91ce27418d3ccb93b3728a6ef3d5/constants.py#L302-L307

### Additional notes

I have no idea whether this is important, but I mention it in case it is needed. For reference, you both changed another hash:

https://github.com/Windows200000/TwitchDropsMiner-updated/blob/69d73bec3acd91ce27418d3ccb93b3728a6ef3d5/constants.py#L308-L316

---

- https://github.com/DevilXD/TwitchDropsMiner/issues/520
- https://github.com/DevilXD/TwitchDropsMiner/commit/0f3a7841b7a99a53ddb9186e2ffc8ef2c18e332d

---

- https://github.com/Windows200000/TwitchDropsMiner-updated/issues/154
- https://github.com/Windows200000/TwitchDropsMiner-updated/commit/54fa81e03804a8bef7aa22e887efefea7c315aeb

**Comment by Windows200000** [comment]
It seems to run fine both with the new and the old one. I will put it into in-dev for now and speed up an update to master if I get crash reports.

Thanks for the help!

**Comment by woctezuma** [comment]
After reading this message, I realize the hash mentioned above may not have to be updated:
- https://github.com/DevilXD/TwitchDropsMiner/issues/519#issuecomment-2243613694

Indeed, it seems only one hash needed to be changed, and the hash mentioned above was a *failed* first attempt.

We will see.

**Comment by Windows200000** [comment]
> After reading this message, I realize the hash mentioned above may not have to be updated:
> 
> * [PersistedQueryNotFound on a CampaignDetails GQL call DevilXD/TwitchDropsMiner#519 (comment)](https://github.com/DevilXD/TwitchDropsMiner/issues/519#issuecomment-2243613694)
> 
> Indeed, it seems only one hash needed to be changed, and the hash mentioned above was a _failed_ first attempt.
> 
> We will see.

The fact he got a new hash there still means this one is more likely to be supported, but as you said, it might also be fine.
