### ISSUE TITLE
Chrome now stops any download of the Windows application

### ISSUE THREAD

**Issue by dogodogowoof** [Windows200000/TwitchDropsMiner-updated#158]
### Description

Chrome now stops any download of the Windows application

### To Reproduce

1. Click the latest release
2. Click Windows

### Expected behavior

The ZIP gets downloaded, and the user starts using the application.the 

### Observed behavior

Chrome stops any download of the Windows application, this goes for the prior release too. On top of Windows Defender blocking the app. That is now a lot of steps blocked. 

### Screenshots

![image](https://github.com/user-attachments/assets/11c9f605-93d6-407a-966a-4cf44909b91c)

### OS

Windows 10

### Build

N/A

### Version/Commit

v15.8.0 (69d73be)

**Comment by Windows200000** [comment]
TDM has always been getting flagged. It's unsigned and Windows defender doesn't like pyinstaller. For more info, look through [issues in the original repo](https://github.com/DevilXD/TwitchDropsMiner/issues?q=is:issue+antivirus).

Unlike DevilXD, I consider modern Windows Defender good, as it has the largest install base and gets automatically updated, so it has a good library of signatures. Unlike some other antiviruses, it's just not as foolproof, but if you are somewhat educated, things like blocking suspicious websites to not download anything in the first place won't be much use to you.

**Comment by Windows200000** [comment]
In case you don't know, you can either confirm the single file in the download menu, or hange chrome settings.

**Comment by dogodogowoof** [comment]
Chrome won't even let me bypass it, even with all workaround attempted.

**Comment by Windows200000** [comment]
> Chrome won't even let me bypass it, even with all workaround attempted.
> 
> Gets instantly deleted, even with things turned off, or forced download

Then it still might be Windows Defender, check that.

**Comment by dogodogowoof** [comment]
I got it to download after pc restart somehow
