### ISSUE TITLE
Add bypass list for campaign account linking.

### ISSUE THREAD

**Issue by Diyagi** [Windows200000/TwitchDropsMiner-updated#179]
### Problem

I will use Palworld as an example.

Maybe because of an bad implementation by Palworld team, the account linking process does not show as linked in twitch despite being linked, you can still mine and receive the drops even tho twitch shows the campaign as not linked.

### Suggestion(s)

My suggesting is to add an list in the settings where games can be added (just like priority list) to bypass campaign account link check.

Yes, this would only be for very special cases and would be good if every camping in twitch just worked, but its not always the case and an bypass list could solve more issues like this in the future.

### Additional notes

![image](https://github.com/user-attachments/assets/dea62db9-c18e-472f-92b9-2c49ea4e9425)
![image](https://github.com/user-attachments/assets/76acce1e-c80f-4213-baee-7d3cb454f7cb)

**Comment by Windows200000** [comment]
This is a duplicate, I don't have the time to find the original for you now, you should be able to search for it.
