### ISSUE TITLE
TDM Unresponsive

### ISSUE THREAD

**Issue by T4bletopG4mes** [Windows200000/TwitchDropsMiner-updated#182]
### Description

TDM becomes unresponsive after adding all campaigns and/or the moment it starts gathering channels. It eventually may get past the problem but there is definitely something there. 

### To Reproduce

Use TDM and have the campaigns I have chosen I guess. 

### Expected behavior

TDM works normally

### Observed behavior

TDM becomes unresponsive.

### Screenshots

![image](https://github.com/user-attachments/assets/0298b4f3-f282-4bd1-8de7-ff7f763b109d)

### Logs

20:07:39: Cannot connect to Twitch, retrying in 33 seconds...
20:07:39: Cannot connect to Twitch, retrying in 34 seconds...
20:07:40: Cannot connect to Twitch, retrying in 34 seconds...
20:07:40: Cannot connect to Twitch, retrying in 8 seconds...
20:07:40: Cannot connect to Twitch, retrying in 31 seconds...
20:07:40: Cannot connect to Twitch, retrying in 31 seconds...
20:07:40: Cannot connect to Twitch, retrying in 29 seconds...

### OS

Windows 10 (64-bit)

### Build

.exe

### Version/Commit

v15.9.1

**Comment by Windows200000** [comment]
What fixed it?

**Comment by T4bletopG4mes** [comment]
Probably fixed itself out/ was twitch's fault

**Comment by Windows200000** [comment]
> Probably fixed itself out/ was twitch's fault

Yh, this just happens occasionally. AFAIK this is a common problem not specific to my fork.
