### ISSUE TITLE
Efficiency after 2024/5 API Change

### ISSUE THREAD

**Issue by Windows200000** [Windows200000/TwitchDropsMiner-updated#3]
(@piz-ewing @Coldblackice Moved this issue here for now. [Original](https://github.com/DevilXD/TwitchDropsMiner/issues/467).)
# What I found:

I added how many (seconds of progress)/watch we get. It's odd.

I guess you could call the less frequent intervals "more efficient", but you aren't getting the progress corresponding to time spent watching, which would not only make the calculation of the remaining time difficult, but more importantly could cause you to miss drops.
> Of course, it's possible that my observations are wrong.I'll measure it tomorrow morning.

I'll be happy to hear how your measurements go.

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/72623832/f07e9e29-606a-4392-8cde-e825c0f571c9)
(Changed the image, the x Axis wasn't to scale)

| Measurements | interval(s) | efficiency | start   | end     | start% | end%   | 100%  | +2%   | -2%   | s/watch +2% | s/watch -2% |
|-------------|-------------|------------|---------|---------|--------|--------|-------|-------|-------|-------------|-------------|
| 1           | 0:00:59     | 0.534      | 10:08:17| 10:35:14| 47.0%  | 59.0%  | 2:00  | 0.623 | 0.445 | 0:00:37     | 0:00:26     |
| 2.1         | 0:00:30     | 0.932      | 10:49:43| 11:01:18| 61.0%  | 70.0%  | 2:00  | 1.140 | 0.725 | 0:00:34     | 0:00:22     |
| 2.2         | 0:00:30     | 0.809      | 11:01:18| 11:08:43| 70.0%  | 75.0%  | 2:00  | 1.133 | 0.485 | 0:00:34     | 0:00:15     |
| 2.3         | 0:00:30     | 1.002      | 11:08:43| 11:15:54| 75.0%  | 81.0%  | 2:00  | 1.336 | 0.668 | 0:00:40     | 0:00:20     |
| 2.4         | 0:00:30     | 0.888      | 11:15:54| 11:26:43| 81.0%  | 89.0%  | 2:00  | 1.109 | 0.666 | 0:00:33     | 0:00:20     |
| 2.5         | 0:00:30     | 0.882      | 11:26:43| 11:53:56| 44.0%  | 54.0%  | 4:00  | 1.058 | 0.705 | 0:00:32     | 0:00:21     |
| 2.all       | 0:00:30     | 0.897      | 10:49:43| 11:53:56| 30.0%  | 54.0%  | 4:00  | 0.972 | 0.822 | 0:00:29     | 0:00:25     |
| 3           | 0:00:15     | 0.861      | 12:12:43| 12:23:52| 54.0%  | 58.0%  | 4:00  | 1.291 | 0.430 | 0:00:19     | 0:00:06     |
| 4           | 0:00:15     | 1.009      | 1:02:07 | 2:27:45 | 47.0%  | 71.0%  | 6:00  | 1.093 | 0.925 | 0:00:16     | 0:00:14     |
| 5           | 0:00:21     | 0.991      | 2:41:40 | 7:14:00 | 50.0%  | 100.0% | 9:00  | 1.031 | 0.952 | 0:00:22     | 0:00:20     |
| 6           | 0:00:25     | 0.967      | 8:45:48 | 13:33:41| 18.0%  | 76.0%  | 8:00  | 1.000 | 0.934 | 0:00:25     | 0:00:23     |

## More info from [original issue](https://github.com/DevilXD/TwitchDropsMiner/issues/467).
> > I added how many (seconds of progress)/watch we get. It's odd.
> > I guess you could call the less frequent intervals "more efficient", but you aren't getting the progress corresponding to time spent watching, which would not only make the calculation of the remaining time difficult, but more importantly could cause you to miss drops.
> > > Of course, it's possible that my observations are wrong.I'll measure it tomorrow morning.
> > 
> > 
> > I'll be happy to hear how your measurements go.
> 
> This is awesome, thanks for doing this and sharing all the above results. Mind if I ask how you're doing this, as far as the test/timings + visualizing as charts? Python/Excel combo? I'd be interested in doing this, as well.

It's in Excel. I had both TDM and the Twitch inventory open. For each test, I changed the frequency in VS Code and ran the miner. I would then take screenshots of both at the same time. Then, I manually entered the measurement index number, Interval and, from those screenshots, the respective progress, time (from the taskbar) and total drop duration. The rest is done with the following formulas. I should note that I let ChatGPT make this table, so it might be messed up somewhere, since it had to compose the table, instead of just formatting it.

| AS           | AT          | AU         | AV    | AW  | AX     | AY   | AZ   | BA  | BB  | BC          | BD          |
|--------------|-------------|------------|-------|-----|--------|------|------|-----|-----|-------------|-------------|
| Measurements | interval(s) | efficiency | start | end | start% | end% | 100% | +2% | -2% | s/watch +2% | s/watch -2% |
| {manual input}            | {manual input} | =(AZ2*(AY2*(AX2/(AW2-AV2)))) | {manual input} | {manual input} | {manual input} | {manual input} | {manual input} | =(AZ2*(AY2+2%-AX2)/(AW2-AV2)) | =(AZ2*(AY2-2%-AX2)/(AW2-AV2)) | =(AZ2*(AY2+2%-AX2))*AT2/(AW2-AV2) | =(AZ2*(AY2-2%-AX2))*AT2/(AW2-AV2) |

edit: The chart is also in Excel, and I had to manually copy the values and change the interval from a time to a general number to make the x-Axis scale correctly.

**Comment by Windows200000** [comment]
Every 20 seconds seems to be the optimal interval.

**Comment by piz-ewing** [comment]
> Every 20 seconds seems to be the optimal interval.

I used an interval of 20 seconds and so far, everything is working fine
