### ISSUE TITLE
 No active campaigns to mine drops for. Waiting for an active campaign...

### ISSUE THREAD

**Issue by aqtoo** [Windows200000/TwitchDropsMiner-updated#38]
![image](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/76844190/f855f170-6257-4cea-95dc-467d10bcba46)

I just wanna farm the minecraft drops and I'm unsure why this isn't working, I've logged in and it's showing no campaigns

**Comment by rvpv** [comment]
@aqtoo look at the settings and add game to Priority list, or unchecked Priority Only checkbox.

**Comment by aqtoo** [comment]
I see the issue, Minecraft is a Open Reward, not a drop, so it doesn't show up, sorry for that!

**Comment by iXerxes** [comment]
@aqtoo if you're talking about the drop for the Minecraft cape, this drop cannot be mined.

The miner will find all games which have an account linked to them. Only these streams are considered valid targets. The Minecraft drop in question however is a special case, as it doesn't require an account to be linked, nor does it report the drop's progress. 

Both of these factors mean it's not possible for the miner to see it as a valid target. You will have to watch it manually. Besides, it's only like 15 minutes watch time, do you really need a miner for this? o.O

**Comment by aqtoo** [comment]
No, I don't need a miner for it but I just thought it'd be worth mentioning
