### ISSUE TITLE
Cannot start on arch linux

### ISSUE THREAD

**Issue by wray-lee** [Windows200000/TwitchDropsMiner-updated#44]
Logs as follows

```bash
Traceback (most recent call last):
  File "main.py", line 196, in <module>
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 649, in run_until_complete
  File "main.py", line 152, in main
  File "twitch.py", line 630, in __init__
  File "gui.py", line 2020, in __init__
  File "gui.py", line 2228, in set_theme
  File "tkinter/ttk.py", line 522, in theme_use
_tkinter.TclError: can't find package ttk::theme::vista
[25710] Failed to execute script 'main' due to unhandled exception!
```

**Comment by Windows200000** [comment]
Thanks for telling me this, as I can't test that. It's an issue with the themes I added as I added dark mode. Will fix.

**Comment by Windows200000** [comment]
@wray-lee Should be fixed, can you please try out the [dev build](https://github.com/Windows200000/TwitchDropsMiner-updated/releases/tag/dev-build) to see if it works, and if switching to **dark mode** as well as **back** applies everything correctly? Thanks!

**Comment by 9ikj** [comment]
Ubuntu 24 works.
![image](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/10474114/99b5aaab-4e56-498a-935c-7e642e2584ff)

**Comment by Windows200000** [comment]
> Ubuntu 24 works. ![image](https://private-user-images.githubusercontent.com/10474114/333347710-99b5aaab-4e56-498a-935c-7e642e2584ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MDA3MjQsIm5iZiI6MTcxNjUwMDQyNCwicGF0aCI6Ii8xMDQ3NDExNC8zMzMzNDc3MTAtOTliNWFhYWItNGU1Ni00OThhLTkzNWMtN2U2NDJlMjU4NGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDIxNDAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4N2VmMjU1MWRhMjkwNTY1ZDAwMzdiODU2MTI0YjY4YjkyN2RjMmFlMDcwNzQ2ZWNmNGM0MzM1MjY2MmViZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pMIffZDnyCCigqZH9SVwdTFhBm6QrCyL9KdIounvdhQ)

Was v15.2.0 broken for you before? Does going from dark to light again work correctly?

**Comment by 9ikj** [comment]
v15.3.0 has the same problem, the dev version works fine.

**Comment by 9ikj** [comment]
> > Ubuntu 24 works.
> 
> @9ikj Was v15.3.0 broken for you before? Does going from dark to light again work correctly?

v15.3.0 has the same problem, the dev version works fine.

**Comment by Windows200000** [comment]
> v15.3.0 has the same problem, the dev version works fine.

Great! I'll make the release. Thanks @wray-lee for reporting the problem and providing logs, and thanks @9ikj for the quick replies confirming the fix.
