### ISSUE TITLE
Exclude impossible campaigns

### ISSUE THREAD

**Issue by Nollasko** [Windows200000/TwitchDropsMiner-updated#64]
I think it would be more effective if the miner did not farm campaigns that would end before the miner could get them

**Comment by Windows200000** [comment]
I think #70 should work, but I am a little scared it could refuse to mine campaigns that are only partly possible.

**Comment by Windows200000** [comment]
![image](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/72623832/32c6b620-f948-4789-9523-a36efe02c66e)
![image](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/72623832/f8cbdffa-f01d-4016-8671-6563287b6c5d)

Yeah....

**Comment by Windows200000** [comment]
![image](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/72623832/0296ac31-0691-4558-b785-5dc04eaf23d7)

It is there, but it's not as straight forward to get to it.

**Comment by Windows200000** [comment]
Well, it needs a function to loop through it and find the lowest. I don't have the time to set that up right now, especially since there are functions with the same name, that do very similar, tho not exactly the same stuff in different classes.

If anyone else can do it, I'll review and merge.

**Comment by Nollasko** [comment]
> @Nollasko thinking on it a bit more, the issue is still that the miner can sometimes incorrectly guess progress, as described in #63. This could then also lead to a minable campaign not being mined.
> 
> I don't think it makes sense to work on this feature until we find a solution to the above-described issue. 

Yeah, of course. I suggested it as a potential feature in the distant future. I'm glad you made TDM work at all and I think you have higher priorities at the moment.
