### ISSUE TITLE
Is it a Trojan?

### ISSUE THREAD

**Issue by Radioaktywn1** [Windows200000/TwitchDropsMiner-updated#68]
![2024](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/45720724/abf4a1e9-eefa-400f-8775-8a900a194db0)

**Comment by Windows200000** [comment]
No, but a lot of Trojans also use compiled python and do network requests. You can't properly trust the releases, as I can upload whatever I want there or replace the EXE generated by GitHub actions, so if you're weary, look at the source and run or compile it yourself.
