### ISSUE TITLE
Window position isn't saved

### ISSUE THREAD

**Issue by Windows200000** [Windows200000/TwitchDropsMiner-updated#7]
### Issue ported from [issue in original repo](https://github.com/DevilXD/TwitchDropsMiner/issues/146)

***
Very tiny annoyance but I use this app on a 2nd monitor and with all the restarts it's starting to become annoying.

**Comment by Windows200000** [comment]
@notNSANE I've got this working, there is however an issue: If you move the window to your second monitor, close TDM, disconnect the monitor and then open TDM, it will forecfully put itself off screen.

I fixed this by not hiding the tray icon when maximized (I was annoyerd by it popping in and out anyways) and adding an option, that just puts it to the top left of the main monitor.

Should be in the latest in-dev soon.

**Comment by Windows200000** [comment]
@notNSANE It's built: [in-dev](https://github.com/Windows200000/TwitchDropsMiner-updated/releases/tag/dev-build)

**Comment by notNSANE** [comment]
beautiful, thanks!

And I believe the disconnect monitor issue is "global" (as in, should happen to most apps).

**Comment by Windows200000** [comment]
@notNSANE
> And I believe the disconnect monitor issue is "global" (as in, should happen to most apps).

Not really. Windows moves apps to your main monitor, if you disconnect one. The issue is only if it changes in between runs, because the window is just forced to be drawn at coordinates, that are now off-screen. I could have fixed this in a cleaner way, but that would require additional dependencies or an OS-dependent solution. I suspect this will be rare anyway, but a simple tray option is nicer than having to manually edit the `.json`, especially as most people wouldn't even think to do that.

**Comment by Windows200000** [comment]
Works on Linux, I'll close this.
