### ISSUE TITLE
help

### ISSUE THREAD

**Issue by EvilRavenOFF** [Windows200000/TwitchDropsMiner-updated#71]
The button is not active when you log into account 2

**Comment by Windows200000** [comment]
You have to be clear about your issue, I have no idea what you're talking about. There are dozens of buttons in the app that can be active or inactive at various times.

**Comment by EvilRavenOFF** [comment]
![image](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/170879393/de418489-0b2d-4b0a-9ce3-337d56a042f2)

**Comment by Windows200000** [comment]
Does it get stuck on that without showing an error in the Output? If so, try removing the `cookies.jar` file and log in again.

**Comment by EvilRavenOFF** [comment]
![image](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/170879393/f89f6267-83da-4fbe-9717-4ee7556af105)
I cannot authorize the second account, the button is not active.

**Comment by Windows200000** [comment]
Read the README.md. It's called README so that you read it and don't ask question answered in it.
