### ISSUE TITLE
Ubisoft f*cked up the Drops for xDefiant (!)

### ISSUE THREAD

**Issue by Shazgul** [Windows200000/TwitchDropsMiner-updated#72]
Edit: See second Post by me, they fcked up the first week drops and deactivate them afterwards.

**Comment by Windows200000** [comment]
How does this look in the twitch side? If they are still there and not progressing, there is nothing I can do. If they were completely removed, they should dissapear from TDM after a reload.

**Comment by Shazgul** [comment]
> How does this look in the twitch side? If they are still there and not progressing, there is nothing I can do. If they were completely removed, they should dissapear from TDM after a reload.

Yep, they're existing, they're just not processing, at first i thought it was an fault by the Drops Farmer, then i investigated the stuff and saw, Ubisoft just fcked. up and now i got these fcked up Drops in my Inventory. :/

![image](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/20743799/da0e23e6-7f69-45b5-b020-00ce2f85feb7)
