### ISSUE TITLE
Docker build

### ISSUE THREAD

**Issue by fireph** [Windows200000/TwitchDropsMiner-updated#79]
I have been using running DevilXD's version (and now yours) for the last few months now in a custom docker container and it has been working amazingly! If you would like to have an official docker image listed in the ReadMe, feel free to use/fork the docker image I made: https://github.com/fireph/docker-twitch-drops-miner

**Comment by Windows200000** [comment]
From README.md:

>TDM is not intended for/as:
>
>- Mining channel points - again, it's about the drops: only. The current points you're getting are a byproduct of getting the drops, not the main goal of it.
>- Mining anything else besides Twitch drops - no, I won't be adding support for a random 3rd party site that also happens to rely on watching Twitch streams.
>- Unattended operation: worst case scenario, it'll stop working and you'll hopefully notice that at some point. Hopefully.
>- 100% uptime application, due to the underlying nature of it, expect fatal errors to happen every so often.
>- Being hosted on a remote server as a 24/7 miner.
>- Being used with more than one managed account.
>- Mining campaigns the managed account isn't linked to.

**Comment by fireph** [comment]
I understand DevilXD's point of view and why they originally wrote this, but the docker container automatically restarts the app when it crashes it works perfectly from my experience for months now. It is completely up to you if you want to maintain this policy, considering the fact the original repo is dormant/dead.
