### ISSUE TITLE
about restarting

### ISSUE THREAD

**Issue by Egorka2017** [Windows200000/TwitchDropsMiner-updated#81]
I can do it with help . " bat " should I restart the program every 4 hours, for example, and put the program on the vps ? Surely nothing should happen?

**Comment by Windows200000** [comment]
It should be fine, but it doesn't support headless. For more info, you can look at discussions in DevilXD's upstream repo.

**Comment by Windows200000** [comment]
@Egorka2017 It should be fine, but it doesn't support headless. For more info, you can look at discussions in DevilXD's upstream repo.

**Comment by Windows200000** [comment]
From README.md:

>TDM is not intended for/as:
>
>- Mining channel points - again, it's about the drops: only. The current points you're getting are a byproduct of getting the drops, not the main goal of it.
>- Mining anything else besides Twitch drops - no, I won't be adding support for a random 3rd party site that also happens to rely on watching Twitch streams.
>- Unattended operation: worst case scenario, it'll stop working and you'll hopefully notice that at some point. Hopefully.
>- 100% uptime application, due to the underlying nature of it, expect fatal errors to happen every so often.
>- Being hosted on a remote server as a 24/7 miner.
>- Being used with more than one managed account.
>- Mining campaigns the managed account isn't linked to.
