### ISSUE TITLE
Too many read/write calls under stress

### ISSUE THREAD

**Issue by Walter-o** [Windows200000/TwitchDropsMiner-updated#89]
Hey!

Today i punched this program into a docker container and ran a few instances but noticed something alarming.

My server's harddrive started to sound like it was going to explode every 10~ seconds.

I could not debug it really thoroughly but here are the facts i have:

- I was hitting tons of rate limiting from twitch
- I limited Websockets to 2 per account but left topics at default 50
- 3 Instances were being ran without proxies
- It only happened after about 30 minutes of running (likely related to rate limiting kicking in gradually)
- It got fixed by switching the cache+lockfile+log to an in-memory (RAM) volume

If i had to guess it's some short circuiting that happens when getting connection errors and then trying to read/write cache.

Anyways, i worked around it but i figured i'd still let you guys know about it, the issue can be closed if needed.

**Comment by Windows200000** [comment]
From README.md:

>TDM is not intended for/as:
>
>- Mining channel points - again, it's about the drops: only. The current points you're getting are a byproduct of getting the drops, not the main goal of it.
>- Mining anything else besides Twitch drops - no, I won't be adding support for a random 3rd party site that also happens to rely on watching Twitch streams.
>- Unattended operation: worst case scenario, it'll stop working and you'll hopefully notice that at some point. Hopefully.
>- 100% uptime application, due to the underlying nature of it, expect fatal errors to happen every so often.
>- Being hosted on a remote server as a 24/7 miner.
>- Being used with more than one managed account.
>- Mining campaigns the managed account isn't linked to.

**Comment by Walter-o** [comment]
- Being hosted on a remote server as a 24/7 miner.
- Being used with more than one managed account.

The context for me violates these 2 guidelines, however the issue also occurs when using 1 account that gets rate limited / connection issues.

Since most people probably run it on windows as desktop application the worst that can happen is if someone has a bad internet connection or twitch has some downtime, it could result in some rapid SSD wear, but since i haven't debugged it yet, i don't know how much r/w cycles it tries to do.

**Comment by Windows200000** [comment]
Duplicate of #23, please add your findings there.
