### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by scryptio** [Windows200000/TwitchDropsMiner-updated#90]
Trying to build the app under windows like always, but since the last release I get an error when starting the app

- setup_env.bat (new clean setup)
- build.bat

```
Traceback (most recent call last):
  File "main.py", line 26, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "twitch.py", line 39, in <module>
ModuleNotFoundError: No module named 'gui'
```

head: 0f42b24864caeabc2af71a651c72f4b1d7fefadd

warn-build
```
invalid module named gui - imported by cache (conditional), twitch (top-level), channel (conditional), websocket (conditional), inventory (conditional)
```

**Comment by Windows200000** [comment]
You should delete all files from the last build. I don't know how in detail, but it does use cached data at some point during the build process if available.

**Comment by scryptio** [comment]
triple checked, still used the wrong python version. multi version always calls for problems. sorry for the call.
