### ISSUE TITLE
various error messages

### ISSUE THREAD

**Issue by matarife123** [Windows200000/TwitchDropsMiner-updated#91]
Today several error messages appeared, but it continues to work without problems

![Sin título](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/110930030/da2a2a89-f1a3-46a5-803a-2849ef88822a)

**Comment by JustaDaydreamWarrior** [comment]
Yeah I've received this error as well. 

> 20:10:42: Watching: QuickyBaby
21:37:11: ERROR: Exception in task
21:37:11: Traceback (most recent call last):
21:37:11:   File "utils.py", line 139, in wrapper
21:37:11:   File "twitch.py", line 1397, in process_drops
21:37:11: asyncio.exceptions.InvalidStateError: invalid state
22:08:17: Fatal error encountered:
22:08:17: 
22:08:17: Traceback (most recent call last):
22:08:17:   File "main.py", line 158, in main
22:08:17:   File "twitch.py", line 772, in run
22:08:17:   File "twitch.py", line 828, in _run
22:08:17:   File "inventory.py", line 232, in claim
22:08:17:   File "inventory.py", line 138, in claim
22:08:17:   File "inventory.py", line 154, in _claim
22:08:17:   File "twitch.py", line 1574, in gql_request
22:08:17: exceptions.MinerException: GQL error: [{'message': 'service error', 'path': ['claimDropRewards']}]
22:08:17: 
22:08:17: Exiting...
22:08:17: 
22:08:17: Application Terminated.
22:08:17: Close the window to exit the application.


At least from what I've been able to test (and replicate), this error seems to happen when TDM tries to auto-claim a drop that has already been claimed (e.g. by an extension like BetterTTV, that also auto-claim drops)

**Comment by Windows200000** [comment]
I'll close this since it looks like expect behavior under certain conditions (from both the code and from DevilXD in issues in the upstream) and the miner continued to work, but thanks for the report.
