### ISSUE TITLE
New app/feature suggestion: "Twitch Points Miner"

### ISSUE THREAD

**Issue by notNSANE** [Windows200000/TwitchDropsMiner-updated#93]
I suggested this to DevilXD but didn't want to do it, so here I am again. 

What I need is an app that farms points from a specific channel. Not sure if multiple channels are possible but only one is more than fine for me.

Basically the app would be either commenting or removing everything regarding Twitch Drops and add a feature to point the farmer to a channel of our choosing. TDM already farms points as a side-feature, so I guessed why not have an app that farms the drops and another one that farms the points?

This is not an easy task of course, and TDM has tons of issues that you guys need to solve first since I don't have the skills to help... so this would be just a nice dream until there's time to fork and maintain this one.

**Comment by Windows200000** [comment]
This is not a fork, but a continuation of TDM and DebilXD intends to return to it, so no.

If I were to take this over I'd write it from scratch in something like rust.
