### ISSUE TITLE
adding a game on your own

### ISSUE THREAD

**Issue by Egorka2017** [Windows200000/TwitchDropsMiner-updated#99]
I added the game to the priority list when the game was not active on twitch. When this game became active on twitch, the drop from this game was not viewed until I added it again. the question is, why do I need an independent addition if it doesn't work. Or I don't understand something

**Comment by Egorka2017** [comment]
The problem is with me, sorry

**Comment by Windows200000** [comment]
@Egorka2017 do I understand, that I can close this issue? You can also do it yourself, if you figured it out.
